### ISSUE TITLE
Why element-plus instead of Vant in mobile development?

### ISSUE THREAD

**Issue by byoungd** [Minori-ty/vite-js-model#1]
As described in title, any explanation?

**Comment by Minori-ty** [comment]
> As described in title, any explanation?

我这个是pc端的模板，移动端确实是用vant

**Comment by byoungd** [comment]
> > As described in title, any explanation?
> 
> 我这个是pc端的模板，移动端确实是用vant

All right. Thanks for building this repo.

**Comment by Minori-ty** [comment]
我将项目重新整理了一下，分成了pc端和移动端，移动端是用vw配置，能够自动检测当前设备，展示不同的页面，感兴趣的话可以看一下
