### ISSUE TITLE
CDN配置出问题了

### ISSUE THREAD

**Issue by chrisworkalx** [Minori-ty/vite-js-model#2]
## 1. 楼主vite构建react16 + antd3老项目，没有配置按需加载报错，请教下该怎么解决
<img width="642" alt="image" src="https://user-images.githubusercontent.com/40884918/176849220-d8fc0c29-be57-4703-a7f6-cc1c36607669.png">

## 2. 我按需加载配置antd3版本，这样dev环境没有报错
![code](https://user-images.githubusercontent.com/40884918/176849893-c4d497d3-efda-47fd-883f-7471dadbf484.png)

## 2.1 但是build还是会报错
<img width="638" alt="image" src="https://user-images.githubusercontent.com/40884918/176850276-a4e33c6c-cd27-4125-876f-0cd1e72a20f1.png">

## 3 基于react18.2.0版本 配置cdn执行build还是会报错
<img width="874" alt="image" src="https://user-images.githubusercontent.com/40884918/176850715-88a626b2-8e57-4f51-b541-48f18dadcc9b.png">

**Comment by Minori-ty** [comment]
global是node的环境变量，也就是之前是用webpack处理的，而webpack可以处理node的环境变量。vite是用esmodule，不能处理node的环境变量，也就是说要么找到你项目中使用的，改成其他的用法。
vite最好的就是从零开始构建，而不是从老项目迁移。
